### DISCUSSION TITLE
How to connect Prometheus?

### DISCUSSION THREAD

**Discussion by imp1sh** [tbnobody/OpenDTU#1230] [Q&A]
I see there is an API query for Prometheus but how do I connect to it?
I have prometheus and Grafana already up and running but do I need some intermediate program that prometheus can scrape the data from? I think I cannot get the data directly from the URL, can I?

**Comment by imp1sh** [comment]
Well it was much easier than I thought it'd be. Since all the other google results were like:
opendtu ---> mqtt broker ---> telegraf ---> InfluxDB ---> Grafana
i was surprosed that it'd also go like this:
opendtu ---> Prometheus ---> Grafana

Here's an example config from prometheus:
```yaml
scrape_configs:
  - job_name: 'opendtu'
    static_configs:
      - targets: ['<<opendtuIP>>:80'] 
    metrics_path: '/api/prometheus/metrics'
    scheme: http  # Use 'http' for HTTP or 'https' for HTTPS
```
