### DISCUSSION TITLE
Confussion: OpenDTU zeigt Änderung an "non-persistant absolute" in "persistant absolute" an (Zero Export / Nulleinspeisung)

### DISCUSSION THREAD

**Discussion by bulkatos** [tbnobody/OpenDTU#1843] [Q&A] [answered]
Hi zusammen,

ich nutze OpenDTU zusammen mit HomeAssistant via MQTT. OpenDTU wurde auch direkt erkannt und kann ohne große Umstände genutzt werden.

In einer Automatisierung in HOAS setze ich alle paar Sekunden den Wert für "non-persistant absolute " auf den aktuellen Energybedarf. Dabei fiel mir auf, das sich auch der Wert für "persistant absolute" ändert. 

Frage:  Ist das nur ein Fehler in der Übermittlung der Daten oder wird tatsächlich ebenfalls der persistant Wert geändert? Das wäre fatal, da damit zu schnell das Limit der Schreibzyklen erreicht wäre.

Viele Dank für eure Antworten.

Falls benötigt, hier meine Automatisierung:
```
alias: Zero Export / Nulleinspeisung
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition:
  - condition: numeric_state
    entity_id: sensor.sun_solar_elevation
    above: 5
action:
  - service: number.set_value
    metadata: {}
    data:
      value: "{{ (states('number.wr_carport_limit_nonpersistent_absolute') | round(0) ) + (states('sensor.hausstrom_summe') | round(0) ) + 150 }}"
    target:
      entity_id: number.wr_carport_limit_nonpersistent_absolute
    enabled: true
mode: single`
```
