### DISCUSSION TITLE
SAX Heimspeicher und openDTU mit 4 Stück HM1500 Daten auslesen

### DISCUSSION THREAD

**Discussion by MiRoGa-NV** [tbnobody/OpenDTU#2127] [Q&A]
Hallo,

ich habe zwei SAX Heimspeicher bei denen das Feld auf dem Paperdisplay für die PV-Leistung nichts anzeigt. Im MQTT-Explorer kann ich AC gesamt aus 4 Invertern sehen., ebenso auf der Web-UI.

Ich stehe in Kontakt mit dem SAX Support und der Techniker schreibt:

`Sie versuchen Ihren WR auszulesen und nennen mir dann: IP, Unit ID, Zieladresse, Scalefaktor, dann kann ich versuchen Ihren Wechselrichter einzubinden und sehen ihn dann in der App unter PV-Leistung.`

Wie komme ich an folgende Werte:
IP:ist bekannt (172.16.xxx.151)
Unit ID : 199980xxxxxx (opendtu)
Zieladresse :  ??
Scalefaktor :  ??

Danke im Voraus für die Hilfe.

Michael

**Comment by stefan123t** [comment]
Hallo @MiRoGa-NV Michael,

Du kannst die AC Werte aus der OpenDTU entweder über deren API oder über MQTT abfragen. Keine Ahnung was der SAX Techniker mit Zieladresse und Scalefaktor eigentlich von Dir will.

Ggf. solltest Du Dir evtl. Das Tochterprojekt OpenDTU-OnBattery ansehen, da werden div. BMS Systeme per CAN/RS485 angebunden und man kann die Ladesteuerung aus der DTU regeln. Du müsstest halt prüfen ob OpenDTU-OnBattery die ModBus Schnittstelle / Register Adressen bereits unterstützt oder ob da noch ein wenig Handarbeit / Konfiguration notwendig ist.

Stefan

**Reply by MiRoGa-NV** [reply]
Hallo Stefan,

er möchte die Registeradressen für Gesamtleistung PV haben und die Unit ID der WR. WR haben aber keine explizite ID, dafür benutze ich ja die openDTU die mit den WR1 bis WR4 über 2.4 GHz kommuniziert.

```
- name: my_battery_2
    type: template
    template: sax
    usage: battery
    modbus: tcpip
    id: 64
    host: 172.16.xxx.154
    port: 502
    
  - name: my_pv
    type: template
    template: hoymiles-opendtu
    usage: pv
    host: 172.16.xxx.151
    port: 502 
```
Michael

**Reply by stefan123t** [reply]
Ja das habe ich vermutet aber OpenDTU und auch OpenDTU-OnBattery bieten Ihrerseits m.W. (noch) keine ModBus Schnittstelle an.
Es gab mal Anfragen dafür https://github.com/tbnobody/OpenDTU/issues/553 aber bisher werden m.W. nur die Daten von Smart Meter / SML oder BMS von OpenDTU-OnBattery konsumiert und zum Steuern des/der Wechselrichter verwendet.

Vielleicht mal ein Feature Request bei OpenDTU-OnBattery aufmachen ?
Die haben wenigstens schon eine ModBus RS485 Schnittstelle auf dem Board.

Für die Original Hoymiles DTU Pro (oder Pro S) gibt es ModBus RTU / RS485 und ModBus TCP über Ethernet.
Beides inkl. der Hoymiles Register Adressen ist in diesem Whitepaper beschrieben: 

**Technical Note - ModBus Implementation using 3rd Gen DTU Pro v1.2**
https://www.shinetech-power.de/wp-content/uploads/2021/07/Technical-Note-Modbus-implementation-using-3Gen-DTU-Pro-V1.2.pdf
Siehe 4.3 Modbus Registers

Aber es gibt wie gesagt m.W. für beides (RTU & TCP) aktuell noch keine Umsetzung auf OpenDTU / OpenDTU-OnBattery.

**Comment by MiRoGa-NV** [comment]
Hallo Stefan,

dies habe ich hier gefunden. Der Modbus ist anscheinend implementiert, allerdings als tcpip Variante.
Das was ich brauche ist der slave (unit) und address: 40192.


gefunden unter pull requests: add modbus #1893
```

modbus:
  ##########################################
  # OpenDTU Hub
  # slave: 1   - Hoymiles DTUPro
  # slave: 125 - OpenDTU Total Inverter (SunSpec)
  - type: tcp
    name: opendtu
    delay: 5
    timeout: 10
    host: 192.168.178.xxx
    port: 502

    sensors:
      - name: "OpenDTU#Total AC Power"
        unique_id: "opendtu_total_ac_power"
        slave: 125
        address: 40192
        input_type: holding
        data_type: float32
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        scan_interval: 10
      - name: "OpenDTU#Total AC Yield Total"
        unique_id: "opendtu_total_ac_yield_total"
        slave: 125
        address: 40202
        input_type: holding
        data_type: float32
        unit_of_measurement: Wh
        device_class: energy
        state_class: total
        scan_interval: 20
      - name: "OpenDTU#Total DC Power"
        unique_id: "opendtu_total_dc_power"
        slave: 125
        address: 40208
        input_type: holding
        data_type: float32
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        scan_interval: 10
```

Michael
