### DISCUSSION TITLE
HM-1500 Limit per RestAPI setzen

### DISCUSSION THREAD

**Discussion by RichardStefan** [tbnobody/OpenDTU#798] [Q&A] [answered]
Hallo Freunde,
ich würde gerne die Limits meinen HM-1500 per RestAPI in HomeAssistant setzen. Diverse Sensoren die auf die OpenDTU zugreifen funktionieren auch via RestAPI problemlos (sprich die GETs). 

Was ich aber nicht zustande bringe ist das POST für das relative Limit (%). Ich hab mir auch das cURL-Beispiel angesehen um es einmal manuell "nachzubauen". Auch hier die cURL funktioniert soweit bei den GETs (auch mit user/password integration), allerdings nicht das POST:

Das Beispiel (IP, user, password und Seriennummer wurden an meine Umgebung angepasst):
`curl -u "admin:password" http://192.168.10.10/api/limit/config -d 'data={"serial":"11418180xxxx", "limit_type":1, "limit_value":50}'`

Das Ergebnis lautet immer:
`{"type":"warning","message":"No values found!","code":1002}`

Sprich, ich kann das Limit aus irgendwelchen Gründen nicht setzen - ich bin mir auch nicht 100% sicher, ob das momentan überhaupt so funktioniert. Aja, ich hab ein Python Script geschrieben, hier funktioniert das setzen des Limit - dh OpenDTU bekommt die richtigen Daten, nur eben nicht via cURL und auch nicht via der RestAPI.

Es gab hier auch ein Posting zu dem Thema mit der selben Frage, allerdings die "Lösung" (missing Content-Type) hilft bei der cURL nicht und auch die RestAPI, die ich mit diesem Content-Type "bestückt" habe, hat so nicht funktioniert. Ich beziehe mich hier auf dieses Posting:
[https://github.com/tbnobody/OpenDTU/discussions/602]

Ich hoffe, jemand kann mir helfen ;-) 
Vielen Dank schon mal,
Richard

**Comment by RichardStefan** [comment, marked as answer]
So, ich hab mir die Frage nun selber beantwortet ... sowohl cURL, alsauch RestAPI funktionieren ...

cURL (wenn aus Windows ausgeführt) - der data-Teil muß in doppelte Hochkomma´s umfasst werden:
`curl -u "admin:password" http://192.168.10.10/api/limit/config -d "data={"serial":"11418180xxxx", "limit_type":1, "limit_value":50}"`

Sollte jemand ein Beispiel für eine RESTful command in HomeAssistant in Verbindung mit der OpenDTU suchen, anbei:
```
zero_export:
  url: "http://<dtu-ip-address>/api/limit/config"
  method: post
  timeout: 30
  verify_ssl: false
  username: admin
  password: <password>
  content_type: application/x-www-form-urlencoded
  payload: 'data={"serial":"11618021xxxx","limit_type":1,"limit_value":50}'
```

Viel Spaß noch & vieeeeelen Dank an die OpenDTU Entwickler für deren unermüdliche Arbeit! Großartig!
Liebe Grüße
Richard
