### ISSUE TITLE
Prometheus syntax error with wifi_bssid

### ISSUE THREAD

**Issue by Gerbyte** [tbnobody/OpenDTU#1021]
### What happened?

After updating to v23.6.9 I get the following error in my Prometheus:
`strconv.ParseFloat: parsing "2C:3A:FD:FD:B1:92": invalid syntax while parsing: "wifi_bssid 2C:3A:FD:FD:B1:92"`
![iScreen Shoter - Safari app - 230610100610](https://github.com/tbnobody/OpenDTU/assets/871068/c6664809-117e-4b48-9599-635a033df8a6)

### To Reproduce Bug

Install version v23.6.9 on the openDTU and query with Prometheus.
The following Scrape Config must be added in Prometheus:

```
  - job_name: "node-exporter-opendtu"
    metrics_path: '/api/prometheus/metrics'
    static_configs:
      - targets: ['IP_of_openDTU']
```

### Expected Behavior

To solve the problem, the metric "wifi_bssid" could be changed to a metric that is recorded as a string instead of a floating point number. This can be achieved by changing the metric type from "gauge" to "label". Here is an example of how the metric "wifi_bssid" can be captured as a string:
```
# TYPE wifi_bssid label
wifi_bssid{value="2C:3A:FD:FD:B0:91"} 1
```

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v23.6.9
